common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    
]

pybo/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static # 이미지를 업로드
from django.urls import re_path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')), # 404 not found 안뜸! 곤
    path('', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('search/', views.search_results, name='search_results'),
    path('myinfo/', views.myinfo, name='myinfo'),
    path('posting_new/', views.posting_new, name='posting_new'),
    path('modify_user/', views.modify_user, name='modify_user'),
    path('post/<int:post_id>/posting_change/', views.posting_change, name='posting_change'),
    path('post/<int:post_id>/posting_delete/', views.posting_delete, name='posting_delete'),
    path('download_image/<int:post_id>/', views.download_image, name='download_image'),
    # path('common:logout/', views.logout_view, name='logout'),
    # re_path(r'^.*$', TemplateView.as_view(template_name="404.html"), name="404"),
    ]

# 이미지 URL 설정
urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

common/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    
    # 사용자의 비밀번호
    password = models.CharField(max_length=20)
    
    # 사용자의 이메일
    email = models.EmailField(max_length=20, blank=True)


    def __str__(self):
        return self.user.username
    

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일", max_length=254)  # 최대 글자수 설정

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    def clean_email(self):
        email = self.cleaned_data.get('email')
        # 이메일 형식이 올바르지 않은 경우 ValidationError 발생
        if '@' not in email:
            raise ValidationError("올바른 이메일 형식이 아닙니다.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        # 유저 이름이 영어, 숫자, '-', '_'로만 이루어져야 함
        if not username.replace('-', '').replace('_', '').isalnum():
            raise ValidationError("아이디는 영어, 숫자, '-', '_'로만 이루어 져야합니다.")
        if len(username) < 5 or len(username) > 20:
            raise ValidationError("아이디는 5자에서 20자 사이어야 합니다.")
        return username
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs['maxlength'] = 20  # 최대 글자수 설정
        self.fields['password2'].widget.attrs['maxlength'] = 20  # 최대 글자수 설정

common/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from common.forms import UserForm
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

def logout_view(request):
    logout(request)
    return redirect('index')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인

            messages.success(request, '')  # 회원가입 성공 메시지 설정

            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
    <!-- 정적 CSS 파일 경로를 설정 -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'login_style.css' %}">
</head>

<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원 가입</title>
    <!-- 정적 CSS 파일 경로를 설정 -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'signup_style.css' %}">
</head>
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">가입하기</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}